2024-01-26 17:08:45,609 INFO    StreamThr :3042408 [internal.py:wandb_internal():86] W&B internal server running at pid: 3042408, started at: 2024-01-26 17:08:45.601282
2024-01-26 17:08:45,619 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status
2024-01-26 17:08:45,620 INFO    WriterThread:3042408 [datastore.py:open_for_write():87] open: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/run-nbvepa2b.wandb
2024-01-26 17:08:45,621 DEBUG   SenderThread:3042408 [sender.py:send():382] send: header
2024-01-26 17:08:45,630 DEBUG   SenderThread:3042408 [sender.py:send():382] send: run
2024-01-26 17:08:46,554 INFO    SenderThread:3042408 [dir_watcher.py:__init__():211] watching files in: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files
2024-01-26 17:08:46,554 INFO    SenderThread:3042408 [sender.py:_start_run_threads():1136] run started: nbvepa2b with start time 1706260125.601119
2024-01-26 17:08:46,558 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: check_version
2024-01-26 17:08:46,559 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: check_version
2024-01-26 17:08:46,926 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: run_start
2024-01-26 17:08:46,959 DEBUG   HandlerThread:3042408 [system_info.py:__init__():27] System info init
2024-01-26 17:08:46,959 DEBUG   HandlerThread:3042408 [system_info.py:__init__():42] System info init done
2024-01-26 17:08:46,959 INFO    HandlerThread:3042408 [system_monitor.py:start():194] Starting system monitor
2024-01-26 17:08:46,969 INFO    SystemMonitor:3042408 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-26 17:08:46,981 INFO    HandlerThread:3042408 [system_monitor.py:probe():214] Collecting system info
2024-01-26 17:08:47,021 INFO    SystemMonitor:3042408 [interfaces.py:start():190] Started cpu monitoring
2024-01-26 17:08:47,034 INFO    SystemMonitor:3042408 [interfaces.py:start():190] Started disk monitoring
2024-01-26 17:08:47,042 INFO    SystemMonitor:3042408 [interfaces.py:start():190] Started gpu monitoring
2024-01-26 17:08:47,059 INFO    SystemMonitor:3042408 [interfaces.py:start():190] Started memory monitoring
2024-01-26 17:08:47,064 INFO    SystemMonitor:3042408 [interfaces.py:start():190] Started network monitoring
2024-01-26 17:08:47,100 DEBUG   HandlerThread:3042408 [system_info.py:probe():151] Probing system
2024-01-26 17:08:47,109 DEBUG   HandlerThread:3042408 [system_info.py:_probe_git():136] Probing git
2024-01-26 17:08:47,126 DEBUG   HandlerThread:3042408 [system_info.py:_probe_git():144] Probing git done
2024-01-26 17:08:47,126 DEBUG   HandlerThread:3042408 [system_info.py:probe():199] Probing system done
2024-01-26 17:08:47,126 DEBUG   HandlerThread:3042408 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.17', 'python': '3.8.17', 'heartbeatAt': '2024-01-26T09:08:47.100735', 'startedAt': '2024-01-26T09:08:45.596485', 'docker': None, 'cuda': None, 'args': ('--local_rank=5', '--config_file', 'config/bert_pretraining_phase2_config.json', '--input_dir', '/home/yanxindong/mkor/bert/data/encoded/sequences_lowercase_max_seq_len_512_next_seq_task_true', '--output_dir', 'results/adam', '--weight_decay', '0.01', '--num_steps_per_checkpoint', '200'), 'state': 'running', 'program': 'run_pretraining.py', 'codePathLocal': 'run_pretraining.py', 'codePath': 'bert/run_pretraining.py', 'git': {'remote': 'https://github.com/kkkjj-d/mkor.git', 'commit': 'efe99e84fef5594780cfb1df6d6a1f61da4ebba0'}, 'email': '1262670315@qq.com', 'root': '/home/yanxindong/mkor', 'host': 'a6000-X640-G40', 'username': 'yanxindong', 'executable': '/home/yanxindong/anaconda/envs/eva/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2091.0454531249998, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3300.003, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 2800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2721.65, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2968.569, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1000.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1200.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3100.0, 'min': 800.0, 'max': 3400.0}, {'current': 2600.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 438.05088806152344, 'used': 28.042591094970703}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 503.51250076293945}}
2024-01-26 17:08:47,126 INFO    HandlerThread:3042408 [system_monitor.py:probe():224] Finished collecting system info
2024-01-26 17:08:47,126 INFO    HandlerThread:3042408 [system_monitor.py:probe():227] Publishing system info
2024-01-26 17:08:47,126 DEBUG   HandlerThread:3042408 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-26 17:08:47,556 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/conda-environment.yaml
2024-01-26 17:08:57,329 DEBUG   HandlerThread:3042408 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-26 17:08:57,331 INFO    HandlerThread:3042408 [system_monitor.py:probe():229] Finished publishing system info
2024-01-26 17:08:57,337 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:57,337 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:57,337 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:57,338 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:57,338 DEBUG   SenderThread:3042408 [sender.py:send():382] send: files
2024-01-26 17:08:57,338 INFO    SenderThread:3042408 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-26 17:08:57,343 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: python_packages
2024-01-26 17:08:57,343 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: python_packages
2024-01-26 17:08:57,382 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:08:57,382 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:08:57,406 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:08:57,559 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/conda-environment.yaml
2024-01-26 17:08:57,559 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/requirements.txt
2024-01-26 17:08:57,559 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/wandb-metadata.json
2024-01-26 17:08:57,690 DEBUG   SenderThread:3042408 [sender.py:send():382] send: telemetry
2024-01-26 17:08:58,308 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb45120d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:08:58,308 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:08:58,308 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:08:59,551 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4512ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:08:59,551 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:08:59,551 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:01,691 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:01,707 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4519400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:01,707 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:09:01,708 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:01,708 INFO    wandb-upload_0:3042408 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbdb4519400>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4519400>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4519400>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:09:06,274 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb45199a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:06,274 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:09:06,274 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:06,692 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:11,692 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:12,366 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:12,367 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:12,413 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:15,974 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4512bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:15,974 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:09:15,974 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:17,674 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:18,565 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/config.yaml
2024-01-26 17:09:23,054 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:27,366 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:27,367 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:27,410 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:28,694 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:33,694 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:34,411 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4512580>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:34,411 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:09:34,411 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:38,695 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:42,366 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:42,367 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:42,410 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:45,743 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:47,064 DEBUG   SystemMonitor:3042408 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-26 17:09:47,068 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:09:51,070 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:56,070 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:57,367 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:57,367 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:57,414 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:01,642 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:06,654 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:11,655 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:12,367 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:12,367 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:12,410 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:13,083 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb45196d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:10:13,083 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:10:13,083 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:10:17,071 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:10:17,074 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:22,073 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:27,074 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:27,367 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:27,367 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:27,414 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:32,642 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:33,659 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/output.log
2024-01-26 17:10:35,660 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/output.log
2024-01-26 17:10:38,185 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:43,186 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:44,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:44,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:44,873 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:47,105 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:10:49,106 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:54,124 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:59,148 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:59,869 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:59,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:04,162 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:09,296 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:14,337 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:14,902 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:14,902 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:17,108 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:11:20,109 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:25,234 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:29,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:29,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:31,201 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:32,383 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4334100>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:11:32,383 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:11:32,383 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:11:36,201 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:41,206 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:44,869 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:44,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:47,110 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:11:47,114 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:52,112 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:57,113 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:59,869 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:59,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:02,187 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:07,324 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:12,380 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:14,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:14,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:17,112 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:12:18,113 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:23,314 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:28,362 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:29,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:29,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:34,212 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:39,254 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:44,313 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:44,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:44,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:47,115 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:12:50,117 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:55,117 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:59,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:59,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:00,171 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:05,172 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:10,173 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:14,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:14,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:15,706 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:17,117 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:13:21,190 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:26,204 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:29,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:29,871 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:31,222 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:36,294 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:41,470 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:44,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:44,870 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:47,124 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:13:47,127 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:52,158 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:57,159 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:59,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:59,871 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:03,148 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:03,627 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb43a3f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:14:03,628 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:14:03,628 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:14:08,149 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:13,150 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:14,870 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:14,871 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:17,122 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:14:19,123 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:24,124 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:29,124 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:29,895 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:29,895 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:34,190 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:39,209 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:44,230 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:44,873 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:44,873 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:44,876 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:14:47,123 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:14:50,153 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:55,203 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:59,906 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:59,906 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:00,215 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:05,216 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:10,216 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:14,873 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:14,873 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:16,172 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:17,126 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:15:22,128 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:27,129 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:29,873 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:29,873 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:32,200 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:37,221 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:40,326 DEBUG   SenderThread:3042408 [sender.py:send():382] send: exit
2024-01-26 17:15:40,326 INFO    SenderThread:3042408 [sender.py:send_exit():589] handling exit code: 1
2024-01-26 17:15:40,326 INFO    SenderThread:3042408 [sender.py:send_exit():591] handling runtime: 413
2024-01-26 17:15:40,326 INFO    SenderThread:3042408 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:40,327 INFO    SenderThread:3042408 [sender.py:send_exit():597] send defer
2024-01-26 17:15:40,327 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:40,327 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 0
2024-01-26 17:15:40,327 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:40,327 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 0
2024-01-26 17:15:40,327 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 1
2024-01-26 17:15:40,328 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:40,328 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 1
2024-01-26 17:15:40,328 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:40,328 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 1
2024-01-26 17:15:40,328 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 2
2024-01-26 17:15:40,328 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:40,328 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 2
2024-01-26 17:15:40,328 INFO    HandlerThread:3042408 [system_monitor.py:finish():203] Stopping system monitor
2024-01-26 17:15:40,328 DEBUG   SystemMonitor:3042408 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-26 17:15:40,328 DEBUG   SystemMonitor:3042408 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-26 17:15:40,331 INFO    HandlerThread:3042408 [interfaces.py:finish():202] Joined cpu monitor
2024-01-26 17:15:40,331 INFO    HandlerThread:3042408 [interfaces.py:finish():202] Joined disk monitor
2024-01-26 17:15:40,450 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/wandb-summary.json
2024-01-26 17:15:42,471 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/output.log
2024-01-26 17:15:42,471 INFO    HandlerThread:3042408 [interfaces.py:finish():202] Joined gpu monitor
2024-01-26 17:15:42,471 INFO    HandlerThread:3042408 [interfaces.py:finish():202] Joined memory monitor
2024-01-26 17:15:42,472 INFO    HandlerThread:3042408 [interfaces.py:finish():202] Joined network monitor
2024-01-26 17:15:42,472 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:42,472 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:42,472 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,473 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 2
2024-01-26 17:15:42,473 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 3
2024-01-26 17:15:42,473 DEBUG   SenderThread:3042408 [sender.py:send():382] send: stats
2024-01-26 17:15:42,474 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:42,474 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,474 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 3
2024-01-26 17:15:42,474 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,474 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 3
2024-01-26 17:15:42,474 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 4
2024-01-26 17:15:42,474 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,474 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 4
2024-01-26 17:15:42,475 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,475 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 4
2024-01-26 17:15:42,475 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 5
2024-01-26 17:15:42,475 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,475 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 5
2024-01-26 17:15:42,475 DEBUG   SenderThread:3042408 [sender.py:send():382] send: summary
2024-01-26 17:15:42,475 INFO    SenderThread:3042408 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:42,476 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,476 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 5
2024-01-26 17:15:42,476 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 6
2024-01-26 17:15:42,476 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,476 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 6
2024-01-26 17:15:42,476 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,476 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 6
2024-01-26 17:15:42,476 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 7
2024-01-26 17:15:42,476 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:42,476 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,476 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 7
2024-01-26 17:15:42,476 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,476 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 7
2024-01-26 17:15:43,325 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:43,471 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/wandb-summary.json
2024-01-26 17:15:44,231 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 8
2024-01-26 17:15:44,232 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:44,232 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:44,232 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 8
2024-01-26 17:15:44,233 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:44,233 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 8
2024-01-26 17:15:44,233 INFO    SenderThread:3042408 [job_builder.py:build():296] Attempting to build job artifact
2024-01-26 17:15:44,234 INFO    SenderThread:3042408 [job_builder.py:_get_source_type():426] is repo sourced job
2024-01-26 17:15:44,259 INFO    SenderThread:3042408 [job_builder.py:build():402] adding wandb-job metadata file
2024-01-26 17:15:44,261 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 9
2024-01-26 17:15:44,262 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:44,262 DEBUG   SenderThread:3042408 [sender.py:send():382] send: artifact
2024-01-26 17:15:44,262 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 9
2024-01-26 17:15:44,326 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:44,472 INFO    Thread-12 :3042408 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/output.log
2024-01-26 17:15:46,726 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb434c370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:46,727 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:46,727 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:46,727 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb434c8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:46,727 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:46,727 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:47,871 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb45190a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:47,872 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:47,872 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:47,890 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4335df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:47,890 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:47,890 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:49,328 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:49,938 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb43562e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:49,938 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:49,938 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:49,938 INFO    wandb-upload_1:3042408 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbdb43562e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb43562e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb43562e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:15:50,254 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4356a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:50,254 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:50,254 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:50,254 INFO    wandb-upload_2:3042408 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbdb4356a90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4356a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4356a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:15:54,330 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:54,438 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4350100>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:54,438 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:54,438 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:55,048 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4356250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:55,048 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:55,049 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:59,332 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:04,081 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb43353a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:04,081 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:04,081 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:04,334 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:04,435 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4335730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:04,436 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:04,436 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:09,336 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:14,338 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:19,341 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:22,119 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4350760>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:22,119 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:22,119 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:23,443 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb43504f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:23,443 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:23,443 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:24,342 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:29,345 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:34,346 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:39,348 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:44,351 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:49,353 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:54,355 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:59,358 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:01,949 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4350c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:01,949 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:17:01,949 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:02,143 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb434c580>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:02,143 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:17:02,143 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:04,359 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:09,362 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:14,369 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:19,371 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:24,373 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:29,375 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:34,379 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:39,380 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:44,383 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:49,385 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:54,388 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:59,390 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:04,392 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:09,394 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:14,396 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:17,630 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/6873c23a2381d1524249eb1a948a45a5?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IJ7jVIe32TjJ7ANYfOstEo%2B0P%2FAflxNObamH3NLb%2F1oM3cnCXRIzfkVEJe2BkBIGpk54hB8b%2BRhiW9SN5RMVNefp%2FaP7JeW6uJBU1kYmDkRiDN2OWgeXjwMst5%2FPJtBZa%2BwEOBxMDN1UljETyGczx3h3M1KUoQxBdp4Rvscd9huNuRjtp%2BHU5as%2B%2Fm2br9PIGhvTeEpn6sAJIZVR%2BGU3y9zMN18A%2F0csE5IG0hMNBNyKoL359zoOJK5ywgZpJExKDdbT7Z9kailufMD%2Bnh82%2FT0D%2FsUT%2FDIPjsckjeW3U4jG3GLzsf9rFnUl%2B3hlE3ByVNAML7sIZjdpzapw8tXtVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb43366d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:17,630 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:18:17,630 ERROR   wandb-upload_2:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:19,397 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:21,449 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789780/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346946&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MuorSEh1emR4FTDaqeItRuD0iBDNY3%2BKoIGDILlmZuvQyJ9%2FTrWOlQZAJpAurAingHeBF1Ck4A5PBjUTeAYcT82sd%2FVGxzISKRIEOaMQ8h8Q9eiZ%2FGmGBQqKPVYmNO3ondyyJ5padinTM3yzvg8d0ZM9uCcB3hqzFnZsPeNzh4OPwOTYb5ZQxyRnBsEU%2BkGCfLw0sVEShe7xtmuo13hp%2Fiwy%2B%2FgIpntg7pIlY%2FQ9b46SHWDPrdPxhejuD8Rc3aGbxJSGt2Lcy%2BdCJiWjhWuA1hLjJpBSQQW6lcgvUCjVtkKICqizU7DX8Xtsx4FhqiFkfqKIXi1loE7XgzQgon971Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb4336190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:21,449 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:18:21,449 ERROR   wandb-upload_1:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:24,399 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:29,401 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:34,403 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:39,405 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:44,407 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:49,409 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:54,411 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:59,413 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:04,416 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:09,417 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:14,419 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:19,422 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:20,015 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/nbvepa2b/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=k8%2FXOfXmF3c4JrATSGHmCGayl6iBSf7cr5yeHzlJAk%2B%2B%2B%2BczC%2B%2F69AG%2BDh3xoXwdsbhdD9H8F9yhMMrXuTQwR1ldx78w49upxs6D6rN%2FCKawFtAfH7yB%2B8QMdM45i7o78BiNRjNI5eLmyls5FSZxyfeJQK4z1ICtHEMJ10iQ9IwPS3Q5Q5eBgwJORD3hPKTJWMnRC0gGaEFSvqRC3MOusGSUtSrPJQIqOZXZMcnMdapqn757Q2n1KgHVnjX43UZr9YS0QTVTx4OEHj3oUcphCPa7KqsHT8oBAydKMAThITw26pL1jnXU5QX%2FV3W4FvN2wfyglxOdTgHjCa98qv3oYA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbdb43564f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:19:20,015 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15618'}
2024-01-26 17:19:20,015 ERROR   wandb-upload_0:3042408 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:19:24,423 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:29,426 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:34,427 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:39,429 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:44,430 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:49,432 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:54,434 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:59,437 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:04,438 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:09,440 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:14,442 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:19,444 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:24,446 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:29,448 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:32,446 INFO    wandb-upload_2:3042408 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmpt3nai9qi
2024-01-26 17:20:34,450 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:39,452 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:44,454 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:45,147 INFO    wandb-upload_1:3042408 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmp9464pi05
2024-01-26 17:20:47,810 INFO    SenderThread:3042408 [sender.py:send_artifact():1494] sent artifact job-https___github.com_kkkjj-d_mkor.git_bert_run_pretraining.py - {'id': 'QXJ0aWZhY3Q6NzAzNzg5Nzgw', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjEzMzk4MTIwMA==', 'latestArtifact': None}}
2024-01-26 17:20:47,810 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:47,810 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:47,810 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 9
2024-01-26 17:20:47,811 INFO    SenderThread:3042408 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-26 17:20:48,518 INFO    SenderThread:3042408 [dir_watcher.py:finish():388] scan: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files
2024-01-26 17:20:48,519 INFO    SenderThread:3042408 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/wandb-summary.json wandb-summary.json
2024-01-26 17:20:48,519 INFO    SenderThread:3042408 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/conda-environment.yaml conda-environment.yaml
2024-01-26 17:20:48,519 INFO    SenderThread:3042408 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/wandb-metadata.json wandb-metadata.json
2024-01-26 17:20:48,519 INFO    SenderThread:3042408 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/output.log output.log
2024-01-26 17:20:48,519 INFO    SenderThread:3042408 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/requirements.txt requirements.txt
2024-01-26 17:20:48,519 INFO    SenderThread:3042408 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/config.yaml config.yaml
2024-01-26 17:20:48,519 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 10
2024-01-26 17:20:48,520 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:48,520 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:20:48,520 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 10
2024-01-26 17:20:48,527 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:48,527 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 10
2024-01-26 17:20:48,527 INFO    SenderThread:3042408 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:20:49,173 INFO    wandb-upload_2:3042408 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/wandb-summary.json
2024-01-26 17:20:49,456 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:49,456 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:49,457 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:49,832 INFO    wandb-upload_4:3042408 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/requirements.txt
2024-01-26 17:20:49,943 INFO    wandb-upload_3:3042408 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/output.log
2024-01-26 17:20:50,014 INFO    wandb-upload_5:3042408 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/config.yaml
2024-01-26 17:20:50,312 INFO    wandb-upload_1:3042408 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/files/conda-environment.yaml
2024-01-26 17:20:50,456 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:50,457 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:51,457 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:51,457 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:52,458 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:52,459 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:53,458 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:53,458 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:53,459 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:54,459 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:54,460 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:55,460 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:55,462 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:56,461 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:56,462 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:57,462 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:57,463 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:58,463 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:58,464 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:58,464 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:59,464 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:59,464 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:00,465 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:00,465 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:01,466 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:01,466 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:02,466 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:02,466 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:03,466 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:03,467 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:03,467 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:04,467 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:04,468 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:05,469 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:05,470 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:06,469 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:06,470 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:07,471 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:07,471 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:08,471 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:08,472 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:08,472 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:09,472 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:09,472 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:10,473 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:10,473 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:11,473 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:11,474 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:12,474 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:12,475 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:13,475 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:13,475 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:13,475 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:14,475 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:14,476 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:15,477 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:15,477 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:16,478 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:16,481 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:17,479 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:17,481 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:18,480 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:18,480 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:18,481 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:19,480 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:19,482 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:20,481 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:20,482 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:21,483 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:21,483 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:22,485 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:22,486 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:23,486 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:23,487 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:23,487 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:24,487 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:24,488 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:25,487 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:25,488 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:26,488 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:26,488 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:27,488 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:27,489 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:28,489 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:28,490 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:28,491 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:29,490 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:29,491 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:30,491 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:30,492 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:31,491 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:31,492 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:32,492 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:32,493 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:33,493 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:33,494 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:33,494 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:34,493 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:34,494 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:35,494 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:35,495 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:36,495 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:36,495 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:37,495 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:37,496 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:38,496 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:38,497 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:38,498 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:39,497 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:39,498 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:40,498 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:40,499 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:41,499 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:41,501 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:42,499 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:42,500 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:43,500 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:43,500 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:43,500 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:44,500 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:44,500 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:45,500 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:45,501 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:46,501 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:46,502 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:47,502 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:47,503 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:48,503 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:48,504 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:48,504 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:49,504 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:49,505 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:50,505 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:50,506 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:51,507 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:51,507 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:52,507 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:52,508 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:53,508 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:53,509 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:53,509 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:54,509 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:54,510 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:55,510 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:55,511 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:56,511 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:56,512 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:57,512 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:57,513 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:58,513 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:58,514 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:58,514 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:59,514 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:59,514 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:00,515 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:00,516 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:01,515 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:01,516 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:02,516 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:02,517 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:03,517 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:03,517 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:03,517 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:04,517 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:04,518 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:05,518 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:05,518 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:06,519 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:06,520 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:07,521 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:07,522 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:08,521 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:08,522 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:08,523 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:09,521 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:09,521 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:10,522 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:10,522 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:11,524 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:11,524 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:12,525 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:12,526 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:13,525 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:13,526 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:13,527 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:14,526 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:14,527 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:15,527 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:15,528 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:16,529 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:16,530 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:17,531 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:17,531 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:18,531 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:18,531 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:18,532 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:19,532 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:19,533 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:20,533 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:20,533 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:21,533 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:21,534 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:22,534 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:22,535 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:23,535 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:23,536 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:23,536 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:24,536 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:24,536 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:25,536 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:25,537 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:26,536 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:26,537 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:27,537 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:27,537 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:28,538 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:28,539 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:28,540 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:29,538 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:29,539 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:30,540 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:30,540 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:31,540 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:31,541 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:32,541 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:32,541 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:33,541 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:33,542 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:33,542 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:34,542 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:34,542 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:35,543 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:35,544 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:36,544 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:36,545 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:37,545 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:37,546 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:38,545 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:38,545 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:38,546 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:39,547 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:39,548 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:40,547 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:40,548 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:41,548 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:41,549 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:42,549 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:42,550 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:43,550 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:43,552 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:43,553 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:44,553 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:44,553 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:45,553 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:45,554 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:46,554 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:46,554 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:47,555 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:47,556 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:48,556 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:48,557 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:48,558 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:49,557 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:49,558 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:50,558 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:50,559 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:51,559 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:51,559 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:52,559 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:52,560 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:53,560 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:53,561 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:53,562 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:54,561 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:54,562 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:55,562 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:55,562 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:56,563 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:56,564 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:57,563 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:57,564 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:58,564 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:58,565 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:58,565 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:59,565 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:59,566 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:00,565 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:00,566 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:01,567 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:01,568 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:02,568 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:02,569 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:03,569 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:03,570 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:03,570 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:04,570 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:04,570 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:05,570 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:05,570 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:06,570 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:06,571 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:07,571 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:07,572 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:08,572 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:08,572 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:08,572 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:09,574 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:09,575 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:10,575 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:10,575 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:11,575 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:11,575 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:12,576 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:12,577 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:13,577 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:13,577 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:13,578 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:14,577 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:14,577 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:15,577 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:15,578 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:16,578 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:16,579 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:17,579 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:17,579 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:18,579 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:18,580 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:18,581 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:19,580 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:19,581 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:20,581 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:20,582 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:21,582 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:21,582 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:22,582 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:22,583 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:23,583 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:23,584 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:23,584 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:24,584 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:24,584 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:25,584 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:25,585 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:26,585 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:26,587 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:27,587 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:27,588 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:28,587 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:28,587 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:28,588 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:29,588 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:29,589 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:30,588 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:30,589 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:31,589 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:31,589 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:32,590 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:32,591 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:33,590 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:33,591 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:33,592 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:34,591 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:34,592 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:35,592 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:35,592 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:36,594 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:36,594 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:37,594 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:37,595 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:38,595 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:38,596 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:38,597 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:39,596 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:39,596 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:40,597 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:40,598 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:41,599 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:41,600 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:42,600 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:42,600 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:43,601 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:43,601 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:43,602 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:44,602 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:44,602 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:45,602 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:45,603 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:46,603 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:46,603 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:47,603 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:47,604 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:48,604 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:48,605 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:48,605 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:49,605 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:49,605 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:50,606 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:50,607 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:51,606 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:51,607 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:52,607 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:52,608 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:53,608 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:53,608 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:53,608 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:54,608 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:54,609 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:55,609 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:55,610 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:56,610 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:56,611 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:57,610 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:57,611 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:58,611 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:58,611 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:58,611 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:59,612 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:59,612 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:00,612 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:00,613 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:01,613 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:01,614 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:02,614 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:02,615 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:03,616 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:03,617 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:03,617 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:04,617 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:04,617 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:05,618 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:05,619 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:06,619 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:06,619 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:07,619 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:07,620 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:08,620 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:08,621 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:08,622 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:09,622 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:09,623 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:10,623 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:10,624 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:11,625 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:11,625 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:12,625 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:12,626 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:13,627 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:13,627 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:13,628 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:14,627 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:14,628 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:15,629 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:15,630 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:16,630 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:16,630 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:17,631 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:17,631 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:18,631 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:18,632 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:18,632 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:19,632 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:19,633 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:20,633 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:20,634 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:21,635 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:21,636 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:22,636 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:22,637 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:23,638 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:23,639 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:23,639 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:24,639 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:24,640 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:25,640 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:25,641 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:26,642 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:26,644 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:27,643 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:27,643 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:28,647 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:28,647 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:28,647 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:29,064 INFO    wandb-upload_0:3042408 [upload_job.py:push():131] Uploaded file /tmp/tmpuck0xnu_wandb/6zz9m6ou-wandb-metadata.json
2024-01-26 17:24:29,264 INFO    Thread-11 :3042408 [sender.py:transition_state():617] send defer: 11
2024-01-26 17:24:29,265 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:24:29,266 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 11
2024-01-26 17:24:29,266 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:24:29,266 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 11
2024-01-26 17:24:29,266 INFO    SenderThread:3042408 [file_pusher.py:join():181] waiting for file pusher
2024-01-26 17:24:29,266 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 12
2024-01-26 17:24:29,267 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:24:29,267 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 12
2024-01-26 17:24:29,267 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:24:29,267 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 12
2024-01-26 17:24:29,267 INFO    SenderThread:3042408 [file_stream.py:finish():595] file stream finish called
2024-01-26 17:24:29,526 INFO    SenderThread:3042408 [file_stream.py:finish():599] file stream finish is done
2024-01-26 17:24:29,526 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 13
2024-01-26 17:24:29,526 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:24:29,526 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 13
2024-01-26 17:24:29,527 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:24:29,527 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 13
2024-01-26 17:24:29,527 INFO    SenderThread:3042408 [sender.py:transition_state():617] send defer: 14
2024-01-26 17:24:29,527 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:24:29,527 INFO    HandlerThread:3042408 [handler.py:handle_request_defer():172] handle defer: 14
2024-01-26 17:24:29,528 DEBUG   SenderThread:3042408 [sender.py:send():382] send: final
2024-01-26 17:24:29,528 DEBUG   SenderThread:3042408 [sender.py:send():382] send: footer
2024-01-26 17:24:29,528 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: defer
2024-01-26 17:24:29,528 INFO    SenderThread:3042408 [sender.py:send_request_defer():613] handle sender defer: 14
2024-01-26 17:24:29,528 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:29,529 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:29,529 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:29,530 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:29,530 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: server_info
2024-01-26 17:24:29,530 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: server_info
2024-01-26 17:24:29,535 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: get_summary
2024-01-26 17:24:29,535 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: sampled_history
2024-01-26 17:24:29,535 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:24:29,535 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: job_info
2024-01-26 17:24:29,805 DEBUG   SenderThread:3042408 [sender.py:send_request():409] send_request: job_info
2024-01-26 17:24:29,805 INFO    MainThread:3042408 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-01-26 17:24:29,805 INFO    MainThread:3042408 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-01-26 17:24:29,806 INFO    MainThread:3042408 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-01-26 17:24:29,807 DEBUG   HandlerThread:3042408 [handler.py:handle_request():146] handle_request: shutdown
2024-01-26 17:24:29,807 INFO    HandlerThread:3042408 [handler.py:finish():869] shutting down handler
2024-01-26 17:24:30,536 INFO    WriterThread:3042408 [datastore.py:close():296] close: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-nbvepa2b/run-nbvepa2b.wandb
2024-01-26 17:24:30,805 INFO    SenderThread:3042408 [sender.py:finish():1572] shutting down sender
2024-01-26 17:24:30,805 INFO    SenderThread:3042408 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:24:30,805 INFO    SenderThread:3042408 [file_pusher.py:join():181] waiting for file pusher
